# Generated by Django 4.2.2 on 2023-09-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0002_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('', 'Selecciona el Tipo de usuario'), ('cliente externo', 'Cliente externo'), ('comerciante local', 'Comerciante local'), ('productor', 'Productor'), ('consultor', 'Consultor'), ('transportista', 'Transportista')], default='', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
