# Generated by Django 4.2.2 on 2023-09-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0003_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
